# Generated by Django 6.0.2 on 2026-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'Enproceso'), ('servido', 'Servido'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
